version: "3"
services:
  api:
    build: .
    container_name: api
    command: uvicorn api:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/zohali:rw
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - zohali-db
      - redis

  zohali-db:
    image: postgres:latest
    container_name: zohali-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_worker
    restart: always
