version: "3.8"
services:
  api:
    build: .
    container_name: api
    command: uvicorn api:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/zohali:rw
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on:
      - zohali-db

  zohali-db:
    image: postgres:latest
    container_name: zohali-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  admin:
    image: adminer
    container_name: admin
    restart: always
    depends_on:
      - zohali-db
    ports:
      - "8080:8080"

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
