version: "3"
services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/zohali:rw
    env_file:
      - .env
    depends_on:
      - zohali-db

  zohali-db:
    image: postgres:latest
    container_name: zohali-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:latest
